services:

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: linokhan/auth-system:latest
    container_name: auth-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=authdb;Username=postgres;Password=adonb_nahk@9991 Path=auth"
      JwtSettings__SecretKey: "a0c022bf03a0df483ebd73cb5aef5c70"
      JwtSettings__Issuer: "AuthServer"
      JwtSettings__Audience: "AuthClient" 
      JwtSettings__ExpireHours: "1"
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adonb_nahk@9991
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
volumes:
  pgdata: