services:

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: linokhan/auth-system:latest
    container_name: auth-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      JwtSettings__SecretKey: "${JWT_SECRET_KEY}"
      JwtSettings__Issuer: "${JWT_ISSUER}"
      JwtSettings__Audience: "${JWT_AUDIENCE}"
      JwtSettings__ExpireHours: "${JWT_EXPIRE_HOURS}"
    depends_on:
      - postgres
  postgres:
    image: postgres:18
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata18:/var/lib/postgresql
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
volumes:
  pgdata18: